1	1	name	taolin
3	1	url	https://taolin.fbk.eu
4	1	admin	admin@example.com
5	1	jsdebug	1
14	1	logo_url	img/logo.png
15	1	favicon	img/favicon.png
7	2	group_name	Group
16	2	publications	1
6	2	domain	example.com
8	3	people_fs_path	/www/html/images/
9	3	error_fs_path	/www/html/images_upload_error/
10	3	people_web_path	img/people/
11	3	webcam_fs_path	/www/html/webcam/
13	4	server	example.com
12	5	method	Dummy
